title: Ramakrishna Nethinti
logo: rknethinti.github.io/rkrk.png
description: Data Scientist/ML Engineer with around 2 years of experience with domain expertise in Finance, Retail, Pharma and Health care. 
show_downloads: False
theme: jekyll-theme-minimal
