title: Ramakrishna Nethinti
logo: /assets/img/headshot_circle.png
description: Data Scientist/ML Engineer with around 2 years of experience with domain expertise in Finance, Retail, Pharma and Health care. 
show_downloads: Fal
theme: jekyll-theme-minimal
